//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesAr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesAr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppResource.MessagesAr", typeof(MessagesAr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متأكد.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمتا المرور غير متطابقتين..
        /// </summary>
        public static string ConfirmPasswordMismatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة مطلوبة.
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء الحذف. الرجاء المحاولة مرة أخرى..
        /// </summary>
        public static string DeleteFailedMessage {
            get {
                return ResourceManager.GetString("DeleteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل الحذف.
        /// </summary>
        public static string DeleteFailedTitle {
            get {
                return ResourceManager.GetString("DeleteFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجاح الحذف.
        /// </summary>
        public static string DeleteSuccessTitle {
            get {
                return ResourceManager.GetString("DeleteSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير صالح..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني مطلوب..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يزيد الاسم الأول عن 50 حرفًا..
        /// </summary>
        public static string FirstNameLength {
            get {
                return ResourceManager.GetString("FirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول مطلوب..
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يزيد اسم العائلة عن 50 حرفًا..
        /// </summary>
        public static string LastNameLength {
            get {
                return ResourceManager.GetString("LastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العائلة مطلوب..
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعطيل حسابك. الرجاء الاتصال بالإدارة..
        /// </summary>
        public static string Message_AccountDeactivated {
            get {
                return ResourceManager.GetString("Message_AccountDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إعادة تفعيل حسابك..
        /// </summary>
        public static string Message_AccountReactivated {
            get {
                return ResourceManager.GetString("Message_AccountReactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الخروج تلقائيًا بسبب عدم النشاط..
        /// </summary>
        public static string Message_AutoLogout {
            get {
                return ResourceManager.GetString("Message_AutoLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ التغييرات بنجاح..
        /// </summary>
        public static string Message_ChangesSaved {
            get {
                return ResourceManager.GetString("Message_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاتصال مفقود. جاري إعادة الاتصال....
        /// </summary>
        public static string Message_ConnectionLost {
            get {
                return ResourceManager.GetString("Message_ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في حذف العنصر. الرجاء المحاولة مرة أخرى..
        /// </summary>
        public static string Message_DeleteFailed {
            get {
                return ResourceManager.GetString("Message_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اكتشاف إدخال مكرر..
        /// </summary>
        public static string Message_DuplicateEntry {
            get {
                return ResourceManager.GetString("Message_DuplicateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل مطلوب..
        /// </summary>
        public static string Message_FieldRequired {
            get {
                return ResourceManager.GetString("Message_FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النموذج غير مكتمل. الرجاء تعبئة جميع الحقول المطلوبة..
        /// </summary>
        public static string Message_FormIncomplete {
            get {
                return ResourceManager.GetString("Message_FormIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال بريد إلكتروني صالح..
        /// </summary>
        public static string Message_InvalidEmail {
            get {
                return ResourceManager.GetString("Message_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال رقم صالح..
        /// </summary>
        public static string Message_InvalidNumber {
            get {
                return ResourceManager.GetString("Message_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العنصر موجود بالفعل..
        /// </summary>
        public static string Message_ItemAlreadyExists {
            get {
                return ResourceManager.GetString("Message_ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العنصر مغلق ولا يمكن تعديله..
        /// </summary>
        public static string Message_ItemLocked {
            get {
                return ResourceManager.GetString("Message_ItemLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد أنك تريد تسجيل الخروج؟.
        /// </summary>
        public static string Message_LogoutConfirmation {
            get {
                return ResourceManager.GetString("Message_LogoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الخروج بنجاح..
        /// </summary>
        public static string Message_LogoutSuccess {
            get {
                return ResourceManager.GetString("Message_LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يتجاوز الإدخال {100} حرفًا..
        /// </summary>
        public static string Message_MaxLengthValidation {
            get {
                return ResourceManager.GetString("Message_MaxLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم اكتشاف تغييرات..
        /// </summary>
        public static string Message_NoChanges {
            get {
                return ResourceManager.GetString("Message_NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت العملية. الرجاء الاتصال بالدعم الفني..
        /// </summary>
        public static string Message_OperationFailed {
            get {
                return ResourceManager.GetString("Message_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون القيمة بين {0} و {1}..
        /// </summary>
        public static string Message_OutOfRangeValidation {
            get {
                return ResourceManager.GetString("Message_OutOfRangeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور بنجاح..
        /// </summary>
        public static string Message_PasswordChanged {
            get {
                return ResourceManager.GetString("Message_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمات المرور غير متطابقة..
        /// </summary>
        public static string Message_PasswordMismatch {
            get {
                return ResourceManager.GetString("Message_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتطلب هذا الإجراء صلاحيات إضافية..
        /// </summary>
        public static string Message_PermissionRequired {
            get {
                return ResourceManager.GetString("Message_PermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم أرشفة السجل..
        /// </summary>
        public static string Message_RecordArchived {
            get {
                return ResourceManager.GetString("Message_RecordArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا السجل مغلق حاليًا للتعديل..
        /// </summary>
        public static string Message_RecordLocked {
            get {
                return ResourceManager.GetString("Message_RecordLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل هذا السجل..
        /// </summary>
        public static string Message_RecordNotEditable {
            get {
                return ResourceManager.GetString("Message_RecordNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استعادة السجل..
        /// </summary>
        public static string Message_RecordRestored {
            get {
                return ResourceManager.GetString("Message_RecordRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت العملية. الرجاء المحاولة مرة أخرى..
        /// </summary>
        public static string Message_Retry {
            get {
                return ResourceManager.GetString("Message_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخادم مشغول حاليًا. الرجاء المحاولة لاحقًا..
        /// </summary>
        public static string Message_ServerBusy {
            get {
                return ResourceManager.GetString("Message_ServerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري رفع الملف. الرجاء الانتظار..
        /// </summary>
        public static string Message_UploadInProgress {
            get {
                return ResourceManager.GetString("Message_UploadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم الملف يتجاوز الحد المسموح به..
        /// </summary>
        public static string Message_UploadSizeLimitExceeded {
            get {
                return ResourceManager.GetString("Message_UploadSizeLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أهلاً بك في لوحة التحكم..
        /// </summary>
        public static string Message_Welcome {
            get {
                return ResourceManager.GetString("Message_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون الإدخال على الأقل {5} حرفًا..
        /// </summary>
        public static string MinLengthValidation {
            get {
                return ResourceManager.GetString("MinLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك ادخل الاسم عربي .
        /// </summary>
        public static string NameArRequired {
            get {
                return ResourceManager.GetString("NameArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك ادخل الاسم انجليزي.
        /// </summary>
        public static string NameEnRequired {
            get {
                return ResourceManager.GetString("NameEnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك ادخل الاسم .
        /// </summary>
        public static string NameOnlyArRequired {
            get {
                return ResourceManager.GetString("NameOnlyArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تتكون كلمة المرور من 8 أحرف على الأقل..
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور مطلوبة..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف غير صالح..
        /// </summary>
        public static string PhoneInvalid {
            get {
                return ResourceManager.GetString("PhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف مطلوب..
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء الحفظ. الرجاء المحاولة مرة أخرى..
        /// </summary>
        public static string SaveFailedMessage {
            get {
                return ResourceManager.GetString("SaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل الحفظ..
        /// </summary>
        public static string SaveFailedTitle {
            get {
                return ResourceManager.GetString("SaveFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح. .
        /// </summary>
        public static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجاح الحفظ.
        /// </summary>
        public static string SaveSuccessTitle {
            get {
                return ResourceManager.GetString("SaveSuccessTitle", resourceCulture);
            }
        }
    }
}
